amazon-corretto-(8.242.07.1|11.0.6.10.1)-8
	* product_downloader: modified detection of curl/wget
	* fix of issue #3

diff --git a/SRC/CLIENT_DATA/product_downloader.sh.in b/SRC/CLIENT_DATA/product_downloader.sh.in
--- a/SRC/CLIENT_DATA/product_downloader.sh.in
+++ b/SRC/CLIENT_DATA/product_downloader.sh.in
@@ -3,8 +3,8 @@
 # Download files from vendor
 # Product: AMAZON CORRETTO
 #
-# Version 1.5.3
-# Jens Boettge <boettge@mpi-halle.mpg.de>  2020-01-15 08:37:13 +0100
+# Version 1.5.4
+# Jens Boettge <boettge@mpi-halle.mpg.de>  2020-01-17 07:42:21 +0100
 #=======================================================================
 # link examples:
 #	INNO:
@@ -24,21 +24,57 @@ DOWNLOADER="curl"
 MD5EXE=$(which md5sum)
 if [ -z "$MD5EXE" ]; then echo "Error: md5sum not found"; exit 200 ; fi
 
-if [ "$DOWNLOADER" = "wget" ]; then
+# --- detect downloader
+case $DOWNLOADER in
+curl)
+	CURL=$(which curl)
+	if [ -z "$CURL" ]; then
+		echo "Warning: Preferred downloader CURL not found. Trying wget."
+		WGET=$(which wget)
+		if [ -z "$WGET" ]; then
+			echo "Error: WGET also not found. Giving up!"
+			exit 201
+		else
+			DOWNLOADER=wget
+		fi
+	fi
+	;;
+wget)
 	WGET=$(which wget)
-	if [ -z "$WGET" ];   then echo "Error: wget not found" ;  exit 201 ; fi
+	if [ -z "$WGET" ]; then
+		echo "Warning: Preferred downloader WGET not found. Trying curl."
+		CURL=$(which curl)
+		if [ -z "$CURL" ]; then
+			echo "Error: CURL also not found. Giving up!"
+			exit 202
+		else
+			DOWNLOADER=curl
+		fi
+	fi
+	;;
+*)
+	echo "Error: none of the supported downloaders (curl, wget) was requested!"
+	exit 203
+	;;
+esac
+
+
+if [ "$DOWNLOADER" = "wget" ]; then
 	#options for wget:
+	DOWNLOADER=$WGET
 	DL_OPTS="--max-redirect=6 --no-cookies -nv "
 	DL_OUT="-O"
 fi
 
 if [ "$DOWNLOADER" = "curl" ]; then
-	CURL=$(which curl)
-	if [ -z "$CURL" ];   then echo "Error: curl not found" ;  exit 202 ; fi
 	#options for curl:
+	DOWNLOADER=$CURL
 	DL_OPTS="--silent --show-error -L "
 	DL_OUT="-o"
 fi
+
+echo "[DBG] DOWNLOADER = $DOWNLOADER"
+# ---
 
 if [ -f "${THIS_DIR}/Makefile" ] ; then
 	# Skript is running in the context of building OPSI package via make
@@ -74,8 +110,8 @@ if [ "{{O_USE_INSTALLER}}" = "MSI" ]; then
 	BASE="{{O_SOFTWARE_DL}}"
 	BASE=${BASE//%%VERSION%%/${VERSION}}
 	PKG_FILE="${BASE##*/}"
-	echo "[DBG] BASE     = $BASE"
-	echo "[DBG] PKG_FILE = $PKG_FILE"
+	echo "[DBG] BASE       = $BASE"
+	echo "[DBG] PKG_FILE   = $PKG_FILE"
 #	### The download page contains CDN links for the msi packages
 #	### Since they may change, we have to parse the file.
 #	declare -A URL=()
